project:
  type: website
  output-dir: docs

website:
  title: "Prayag Gordy"

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    page-layout: full

editor: visual

